Repository wcmc-its/ReCiter-Publication-Manager, pull requests merged in 2022-02, with the labels that each got.

#120 Search app bug fixes
  src/components/elements/Profile/Profile.tsx
  src/components/elements/Publication/HistoryModal.tsx
  src/utils/filterPublications.js
Labels: bug, enhancement

#122 Feature/group view banner
  src/components/elements/CurateIndividual/SuggestionsBanner.tsx
  src/components/elements/Publication/PublicationsPane.tsx
  src/redux/actions/actions.js
  src/redux/methods/methods.js
  src/redux/reducers/reducers.js
Labels: enhancement

#134 Fix for name search filter and personType filter fix
  controllers/db/person.controller.ts
Labels: bug
