Repository wcmc-its/ReCiter-Publication-Manager, pull requests merged in 2022-01, with the labels that each got.

#108 Feedback log and adminUser apis
  controllers/db/admin.feedbacklog.controller.ts
  controllers/db/admin.users.controller.ts
  controllers/db/person.controller.ts
  src/db/models/AdminDepartment.ts
  src/db/models/AdminFeedbackLog.ts
  src/db/models/AdminNotificationLog.ts
  src/db/models/AdminNotificationPreference.ts
  src/db/models/AdminRole.ts
  src/db/models/AdminUser.ts
  src/db/models/AdminUsersDepartment.ts
  src/db/models/AdminUsersRole.ts
  src/db/models/Altmetric.ts
  src/db/models/init-models.ts
  src/pages/api/auth/[...nextauth].jsx
  src/pages/api/db/admin/feedbacklog/[uid].ts
  src/pages/api/db/admin/feedbacklog/create/index.ts
  types/next-auth.d.ts
Labels: enhancement

#109 Feature/group view
  src/components/elements/Common/Loader.tsx
  src/components/elements/CuratePublications/CuratePublications.module.css
  src/components/elements/CuratePublications/CuratePublications.tsx
  src/components/elements/Navbar/MenuListItem.tsx
  src/components/elements/Navbar/Navbar.module.css
  src/components/elements/Navbar/SideNavbar.tsx
  src/components/elements/Publication/Publication.module.css
  src/components/elements/Publication/Publication.tsx
  src/components/elements/Publication/PublicationsPane.tsx
  src/components/elements/Search/Search.js
  src/components/elements/Search/Search.module.css
  src/redux/actions/actions.js
  src/redux/methods/methods.js
  src/redux/reducers/reducers.js
  src/utils/fullName.js
  types/Author.d.ts
  types/menu.d.ts
Labels: bug, enhancement

#110 Search fixes
  src/components/elements/Search/Search.js
  src/components/elements/Search/SearchBar.tsx
Labels: bug

#111 Feature/group view
  src/components/elements/Common/Divider.tsx
  src/components/elements/Common/Styles.module.css
  src/components/elements/CuratePublications/CuratePublications.tsx
  src/components/elements/Publication/Publication.tsx
  src/components/elements/Publication/PublicationsPane.tsx
Labels: bug, enhancement

#112 evidence name error fix
  src/components/elements/Publication/Publication.module.css
  src/components/elements/Publication/Publication.tsx
  src/components/elements/Publication/PublicationsPane.tsx
Labels: bug

#114 WCM saml changes
  config/certs/.ignore
  config/saml.ts
  k8-buildspec.yml
  kubernetes/k8-deployment.yaml
  package.json
  src/components/elements/Header/Header.tsx
  src/components/elements/Login/Login.js
  src/pages/api/auth/[...nextauth].jsx
  src/pages/api/healthcheck.ts
  src/pages/api/saml/assert.ts
  src/utils/loginHelper.ts
Labels: bug, enhancement

#119 Feature/app page
  .gitignore
  src/components/elements/CurateIndividual/CurateIndividual.module.css
  src/components/elements/CurateIndividual/CurateIndividual.tsx
  src/components/elements/CurateIndividual/FilterPubSection.tsx
  src/components/elements/CurateIndividual/InferredKeywords.tsx
  src/components/elements/CurateIndividual/ReciterTabContent.tsx
  src/components/elements/CurateIndividual/ReciterTabs.tsx
  src/components/elements/CuratePublications/CuratePublications.tsx
  src/components/elements/Pagination/Pagination.module.css
  src/components/elements/Publication/HistoryModal.tsx
  src/components/elements/Publication/Publication.tsx
  src/components/elements/Publication/PublicationsPane.tsx
  src/components/elements/Search/Search.js
  src/redux/actions/actions.js
  src/redux/methods/methods.js
  src/redux/reducers/reducers.js
  src/utils/filterPublicationsBySearchText.js
  types/publication.d.ts
Labels: bug, enhancement
